//
//  SQLPrepareStatement.h
//  FlightKit
//
//  Created by Daniel Vancura on 1/14/18.
//  Copyright © 2018 Daniel Vancura. All rights reserved.
//

#ifndef SQLPrepareStatement_h
#define SQLPrepareStatement_h

#define SQL_PREPARE_STATEMENT "CREATE TABLE IF NOT EXISTS RECORDING\
(TIMESTAMP INT PRIMARY KEY ASC ON CONFLICT REPLACE,\
THROTTLE_SETTING REAL,\
MIXTURE_SETTING REAL,\
PROP_SETTING REAL,\
FLAP_SETTING REAL,\
ELEVATOR_SETTING REAL,\
AILERON_SETTING REAL,\
RUDDER_SETTING REAL,\
ELEVATOR_TRIM_SETTING REAL,\
AILERON_TRIM_SETTING REAL,\
RUDDER_TRIM_SETTING REAL,\
HEADING_COMPASS REAL,\
INDICATED_ALTITUDE REAL,\
INDICATED_AIRSPEED REAL,\
VERTICAL_VELOCITY REAL,\
LATITUDE REAL,\
LONGITUDE REAL);"

#endif /* SQLPrepareStatement_h */
